"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.division = exports.multiplication = exports.minus = exports.plus = exports.sum = void 0;
const sum = (numbers) => numbers.reduce((total, number) => total + number, 0);
exports.sum = sum;
const plus = (a, b) => a + b;
exports.plus = plus;
const minus = (a, b) => a - b;
exports.minus = minus;
const multiplication = (a, b) => a * b;
exports.multiplication = multiplication;
const division = (a, b) => a / b;
exports.division = division;
const calc = { division: exports.division, minus: exports.minus, multiplication: exports.multiplication, plus: exports.plus, sum: exports.sum };
exports.default = calc;
